chore!: deprecate `browser` param
ChainSafe/dappeteer pull request #282
Opened 2023-02-13 19:05 UTC by BeroBurny

**Short description of work done**

### PR Checklist

- [ ] I have run linter locally
- [ ] I have run unit and integration tests locally
  - [ ] Update configuration the newest version (readme and const)
- [ ] Rebased to master branch / merged master

### Changes

- _EXAMPLE - Removed basic auth from the controller_

### Issues

Closes #280

2023-02-13 19:49 UTC, Lykhoyda requested changes
looks good, just small fix with operator required

2023-02-13 19:57 UTC, BeroBurny commented on src/setup/launch.ts
> +        Headless: ${String(options.headless || true)}
good point, removed from this PR as is not part of it

2023-02-14 09:26 UTC, irubido approved these changes

2023-02-14 14:42 UTC, Lykhoyda approved these changes

2023-02-14 14:43 UTC, merged