fix: add evaluate element click for closeWhatsNewModal
ChainSafe/dappeteer pull request #346
Opened 2023-09-19 11:20 UTC by marijanabevanda

**Short description of work done**
Fixing 'Node is Detached from Document' Error in Puppeteer/Dappeteer Code: Refactoring closeWhatsNewModal Logic

### PR Checklist

- [ ] I have run linter locally
- [ ] I have run unit and integration tests locally
- [ ] Update configuration the newest version (readme and const)
- [ ] Rebased to master branch / merged master

### Changes

I encountered an intermittent 'Node is detached from document' error while using the closeWhatsNewModal method. This issue occurred sporadically due to the dynamic nature of the application, where the close button was deleted and recreated.

To address this problem, I implemented a solution similar to what was used in the closePopup method. Specifically, I introduced a new method called evaluateElementClick that contains the necessary logic. This method includes a 1-second delay to handle scenarios where elements are dynamically recreated. Both closePopup and closeWhatsNewModal methods now use evaluateElementClick.

(Added new pull request because last wasn't working with cla)

Error solved:
![image](https://github.com/ChainSafe/dappeteer/assets/54986853/e6cceb08-1911-4c27-b55b-34c34d5c881d)

### Issues

Closes #

2023-09-21 11:52 UTC, irubido requested changes
Indeed, happens sometimes, good fix. Just fix lint for CI to pass.

2023-09-25 13:00 UTC, marijanabevanda commented
I don't know why Playwright is failing. The error seems (and should be) unrelated to my recent changes, and I've also encountered it on the master branch.

Playwright error:
![image](https://github.com/ChainSafe/dappeteer/assets/54986853/8bdcac06-3728-449d-95e8-e7356501c1f7)

Local error on master branch:
![image](https://github.com/ChainSafe/dappeteer/assets/54986853/455612e8-30df-40ca-81ce-585fc013ce8b)

2023-09-26 11:08 UTC, irubido approved these changes

2023-09-26 11:13 UTC, irubido commented
> I don't know why Playwright is failing. The error seems (and should be) unrelated to my recent changes, and I've also encountered another on the master branch.
> 
> Playwright error: ![image](https://user-images.githubusercontent.com/54986853/270347684-8bdcac06-3728-449d-95e8-e7356501c1f7.png)
> 
> Local error on master branch: ![image](https://user-images.githubusercontent.com/54986853/270348672-455612e8-30df-40ca-81ce-585fc013ce8b.png)

I'm aware of that issue, working on a dappeter update to latest mm version, so it will be addressed in upcoming PR.

2023-09-26 11:14 UTC, merged